### ISSUE TITLE
Compression seems to break volumetry dashboard

### ISSUE THREAD

**Issue by coppee-p** [marcanpilami/mongodb-collector#30] opened 2016-11-04 10:45 UTC
![image](https://cloud.githubusercontent.com/assets/1093826/20003004/2805c6b6-a284-11e6-8b5a-41ba1007469b.png)

**Comment by marcanpilami** [comment] 2016-11-07 10:35
Duplicate of #29.

**Closed as completed by marcanpilami** 2016-11-07 10:35 UTC
